#!/bin/bash

if [[ $# -ne 1 ]]
then
    echo "Usage: tmr get; tmr submit"
    exit
fi

if [[ -z "$XDG_HOME_CONFIG" ]]
then
    CONF_FILE="$HOME/.config/tmr"
else
    CONF_FILE="$XDG_HOME_CONFIG/tmr"
fi

if [[ ! -f "$CONF_FILE" ]]
then
    echo "Please create $CONF_FILE"
    exit
fi
source "$CONF_FILE"

case "$1" in
    "get" )
        mv "$SAVEFILE" "$SAVEFILE.old"
        curl "$BASE_URL/api/Diplomacy/GetLatestSaveFileBytes?authKey=$AUTH_KEY&gameId=$GAME_ID" -o "$SAVEFILE"
        ;;
    "submit" )
        PLAYER_ID=$(curl -s "$BASE_URL/api/Diplomacy/AuthenticateUser?authKey=$AUTH_KEY")
        TURN_ID=$(curl -s "$BASE_URL/api/Diplomacy/GetGamesAndPlayers?playerIDText=$PLAYER_ID&authKey=$AUTH_KEY" \
            | jq ".Games | map(select( .GameId == $GAME_ID))[0].CurrentTurn.TurnId")
        curl -F "turnId=$TURN_ID" -F "isCompressed=False" -F "authKey=$AUTH_KEY" -F "saveFileUpload=@$SAVEFILE" \
             "$BASE_URL/Game/UploadSaveClient"
        ;;
esac
